twig:
    file_name_pattern: '*.twig'
    globals:
        tenor_api_key: '%env(TENOR_API)%'
    form_themes: ['bootstrap_5_layout.html.twig']
    cache: false
when@test:
    twig:
        strict_variables: true
